- name: Deploy DB+UI Server
  hosts: localhost
  gather_facts: no
  connection: local
  become: yes
  vars:
    git_user: "ian8dev"
    git_repo: "devops-fullstack"
    git_token: "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"
    dest_folder: "/opt/deploy1/"
    ansible_become_pass: "y%cWP2ZMvn6$jYU"
  tasks:
  # This should be reconfigured if using plain ubuntu linux servers.
  # The current setup is on a windows laptop with WSL2 installed.
    # - name: Install docker and docker compose
    #   apt:
    #     name: docker.io docker-compose
    #     state: present
    #     update_cache: yes
    # ==============================================================

    - name: Stop+Delete containers
      ansible.builtin.command:
        cmd: '/mnt/c/Program\ Files/Docker/Docker/resources/bin/docker-compose.exe -f devops/docker-compose.yml rm -s -f -v'
      become: yes
      args:
        chdir: /opt/deploy1/
    - name: collect files in target path
      ansible.builtin.find:
        paths: "/opt/deploy1"
        hidden: true
        recurse: true
        file_type: any
      register: collected_files
    - name: remove collected files
      file:
        path: "{{ item.path }}"
        state: absent
      with_items: >
        {{
          collected_files.files
        }}
    - name: Clone the repository
      ansible.builtin.git:
        repo: "https://{{ git_token }}@github.com/{{ git_user }}/{{ git_repo }}.git"
        dest: "/opt/deploy1/"
        version: main
        clone: yes
        update: yes
        force: yes
      become: yes
    - name: Start the Application
      ansible.builtin.command:
        cmd: '/mnt/c/Program\ Files/Docker/Docker/resources/bin/docker-compose.exe -f devops/docker-compose.yml up db phpmyadmin -d --build'
      become: yes
      args:
        chdir: /opt/deploy1/
