services:
  db:
    image: mysql:latest
    restart: always
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: devopsfs-mysql-secret
      MYSQL_DATABASE: app_db
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_user_pass
    ports:
      - "6033:3306"
    volumes:
      - dbdata:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 0
    restart: always
    ports:
      - 8081:80
    depends_on:
      - db
  web1:
    image: nginx:latest
    ports:
      - "8091:80"
  web2:
    image: nginx:latest
    ports:
      - "8092:80"
volumes:
  dbdata: